ci: test failure

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -24,7 +24,10 @@ jobs:
             platforms: linux/amd64
             required: true
           - os: ubuntu-24.04-arm
-            platforms: linux/arm64,linux/arm/v7
+            platforms: linux/arm64
+            required: true
+          - os: ubuntu-24.04-arm
+            platforms: linux/arm/v7
             required: false
     continue-on-error: ${{ !matrix.required }}
     runs-on: ${{ matrix.os }}
@@ -35,6 +38,11 @@ jobs:
           echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
           echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV
       - uses: actions/checkout@v4
+      - name: Test failure
+        if: ${{ !matrix.required }}
+        run: |
+          echo "Intentionally failing step"
+          exit 1
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
